/*
* Membrane Software Reference Source License
* Version 2024 Sep 18
* This license is a legal agreement between you and Membrane Software
*
* This license agreement governs use of the accompanying source code. If you use the source code, you accept this license. If you do not accept the license, do not use the source code.
*
* DEFINITIONS
* "compilation" means to compile the code from source code to machine code.
* “non-commercial distribution” means distribution of the code or any compilation of the code, or of any other application or program containing the code or any compilation of the code, where such distribution is not intended for or directed towards commercial advantage or monetary compensation.
* "review" means to access, analyse, test and otherwise review the code as a reference
* "you" means the licensee of rights set out in this license.
*
* GRANT OF RIGHTS
* Subject to the terms of this license, we grant you a non-transferable, non-exclusive, worldwide, royalty-free license to access and use the source code solely for the purposes of review, compilation and non-commercial distribution.
*
* LIMITATIONS
* This license does not grant you any rights to use Membrane Software's name, logo, or trademarks.
*
* If you issue proceedings in any jurisdiction against Membrane Software because you consider Membrane Software has infringed copyright or any patent right in respect of the code (including any joinder or counterclaim), your license to the code is automatically terminated.
*
* This source code is provided by the copyright holders and contributors "as is" and any express or implied warranties, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose are disclaimed. In no event shall the copyright holder or contributors be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this source code, even if advised of the possibility of such damage.
*
* NO IMPLIED RIGHTS
* All rights not expressly granted by Membrane Software to you in this License Agreement are hereby reserved by Membrane Software and its suppliers. There are no implied rights in this License Agreement.
*
* GOVERNING LAW
* This EULA agreement, and any dispute arising out of or in connection with this EULA agreement, shall be governed by and construed in accordance with the laws of Washington State, United States of America.
*
* QUESTIONS OR ADDITIONAL INFORMATION
* If you have questions regarding this License Agreement, please contact Membrane Software by sending an email to support@membranesoftware.com.
*/
// Class that holds a set of frame textures
#ifndef SPRITE_H
#define SPRITE_H

class Sprite {
public:
	Sprite ();
	virtual ~Sprite ();

	// Read-only data members
	int frameCount;
	int maxWidth, maxHeight;
	int64_t pixelCount;
	double minRenderScale;
	double maxRenderScale;
	double renderScaleIncrement;

	// Return a newly created Sprite object with its own copies of all resources referenced by this object, or NULL if the copy could not be created
	Sprite *copy ();

	// Load sprite data from numbered png files at the specified path and return a Result value. If imagePrefix is not provided, use the App imagePrefix value.
	OpResult load (const StdString &path, const StdString &imagePrefix = StdString ());

	// Load sprite data as a series of scaled images generated by pixel render functions and return a Result value
	OpResult load (double minScale, double maxScale, double scaleIncrement);

	// Add the provided texture to the sprite's frame set. When the sprite is unloaded, release it from resources using the specified loadPath. Returns a Result value.
	OpResult addTexture (SDL_Texture *texture, const StdString &loadPath);

	// Unload previously loaded sprite data
	void unload ();

	// Return the SDL_Texture object at the specified index, or NULL if no such texture was found. If a texture is found, write texture attributes to any provided pointer values.
	SDL_Texture *getTexture (int index, int *width = NULL, int *height = NULL, StdString *loadPath = NULL) const;

	// Return the SDL_Texture object at the specified render scale, or NULL if no such texture was found. If a texture is found and int pointers are provided, those values are filled in with texture attributes.
	SDL_Texture *getScaleTexture (double scale, int *width = NULL, int *height = NULL, int *frameIndex = NULL) const;

	// Return the load path for the texture at the specified index, or an empty string if no such texture was found
	StdString getLoadPath (int index) const;

protected:
	// Set frameWidth and frameHeight to values appropriate for the scale
	virtual void getRenderFrameSize (double scale, double *frameWidth, double *frameHeight);

	// Write render data to the provided pixels buffer
	virtual void writeRenderPixels (double scale, Uint32 *pixels, double frameWidth, double frameHeight);

	struct TextureData {
		SDL_Texture *texture;
		StdString loadPath;
		int width, height;
		TextureData ():
			texture (NULL),
			loadPath (""),
			width (0),
			height (0) { }
	};
	std::vector<Sprite::TextureData> textureList;
};
#endif
